import Homepage from "@/components/Homepage/Homepage";
import Header from "@/components/Header/Header";
import styles from "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function App() {
  return (
    <>
      <main className={styles.main}>
        <div>
          <Header />
          <Homepage />
        </div>
      </main>
    </>
  );
}

export default App;
